export const WHATSAPP_NUMBER = '918887878193';

// Converts a Google Drive file ID to a displayable thumbnail URL.
// Make sure your H.M Diamond folder is shared as "Anyone with the link can view".
const gd = (id) => `https://drive.google.com/thumbnail?id=${id}&sz=w400`;

export const STATS = [
  { num: '15+', label: 'Years' },
  { num: '5000+', label: 'Clients' },
  { num: '2000+', label: 'Designs' },
  { num: '10+', label: 'Cities' },
];

export const CATEGORIES = [
  { id: 'all',         label: 'All' },
  { id: 'rings',       label: 'Gents Ring' },
  { id: 'earrings',    label: 'Earrings' },
  { id: 'bangles',     label: 'Bangles' },
  { id: 'necklaces',   label: 'Necklaces' },
  { id: 'pendants',    label: 'Pendants' },
  { id: 'tops',        label: 'Tops' },
  { id: 'bracelets',   label: 'Bracelets' },
  { id: 'nosepin',     label: 'Nose Pin' },
  { id: 'ladiesring',  label: 'Ladies Ring' },
  { id: 'ladiesbangles', label: 'Ladies Bangles' },
  { id: 'pendantset',  label: 'Pendant Set' },
  { id: 'ms',          label: 'Mangalsutra' },
];

export const PRODUCTS = [
  // ── Gents Rings (GR) ─────────────────────────────────────────────────────
  { id: 1,   name: 'Gents Ring', code: 'GR-1003', category: 'rings', image: gd('1CsiapsmLF1I8XhOalHjqt63n7UV6uvbL') },
  { id: 2,   name: 'Gents Ring', code: 'GR-1026', category: 'rings', image: gd('1qSXYUDa1vi18qymCO4YRJ5U7UpFAFEiR') },
  { id: 3,   name: 'Gents Ring', code: 'GR-1029', category: 'rings', image: gd('1EUiTT0KRIbkJemK2misLBXdgCiHy_IXL') },
  { id: 4,   name: 'Gents Ring', code: 'GR-1030', category: 'rings', image: gd('1ysuOupqnHWYMBQAKFS93ghQ1qNgjl4yx') },
  { id: 5,   name: 'Gents Ring', code: 'GR-1032', category: 'rings', image: gd('100Db6347WKiBWQrCWPZFwt2vv-28FNku') },
  { id: 6,   name: 'Gents Ring', code: 'GR-1033', category: 'rings', image: gd('11n9yjpATiq-7-RUWvFTzZvVvwo8Jj6Zx') },
  { id: 7,   name: 'Gents Ring', code: 'GR-1034', category: 'rings', image: gd('15gAiPNiBijCItr-9jjf-QOWDen24GuYP') },
  { id: 8,   name: 'Gents Ring', code: 'GR-1035', category: 'rings', image: gd('1SW8Uq0d2Fs37JXXz6PItfWvYc6KujTrJ') },
  { id: 9,   name: 'Gents Ring', code: 'GR-1036', category: 'rings', image: gd('1n-l8kXwxHHL7RSslGAWG-vktVXjWR_lV') },
  { id: 10,  name: 'Gents Ring', code: 'GR-1037', category: 'rings', image: gd('1yxGb_h-o2s3Ox8qfV8S2YxKdiQSmRniH') },
  { id: 11,  name: 'Gents Ring', code: 'GR-1038', category: 'rings', image: gd('10tjVbuL72oEuJWItHXo7b49aTp9OzTKJ') },
  { id: 12,  name: 'Gents Ring', code: 'GR-1039', category: 'rings', image: gd('11aMsJ9RYnVYfGIhqQevsbJWvCwlLzrQM') },
  { id: 13,  name: 'Gents Ring', code: 'GR-1040', category: 'rings', image: gd('1S32bG6SvF1S0UtLnqryBzpzhAxBhd9-f') },
  { id: 14,  name: 'Gents Ring', code: 'GR-1041', category: 'rings', image: gd('1MnC5RsLP1J3DrKqRHoKvhz2nGyCQyPQS') },
  { id: 15,  name: 'Gents Ring', code: 'GR-1042', category: 'rings', image: gd('1Ppfu9CpAgaunTTqmGAztDH0BgPtjN5ab') },
  { id: 16,  name: 'Gents Ring', code: 'GR-1043', category: 'rings', image: gd('1rXbR0zFojVTRaU_xvWc22Je1eXqO6XDI') },
  { id: 17,  name: 'Gents Ring', code: 'GR-1044', category: 'rings', image: gd('1AuWJoKlUByEmC9qH-N3ZFrV_ryE77YIp') },
  { id: 18,  name: 'Gents Ring', code: 'GR-1045', category: 'rings', image: gd('1vNhqnqvN1zq9ur8muod9evLWU-S4U75N') },
  { id: 19,  name: 'Gents Ring', code: 'GR-1046', category: 'rings', image: gd('1ldSDpTWCZfANVPp0gIJF8wE3qYTczerx') },
  { id: 20,  name: 'Gents Ring', code: 'GR-1047', category: 'rings', image: gd('1xbj_7EJJCV15uJclrmLOneuuiIXFVGdy') },
  { id: 21,  name: 'Gents Ring', code: 'GR-1048', category: 'rings', image: gd('1UWUi3EmQ1mTUg3MuxfueJqSusaTzR6rI') },
  { id: 22,  name: 'Gents Ring', code: 'GR-1049', category: 'rings', image: gd('1pM57lpl3iEIZSJ7Rd_SuV-L8ug8ygDeE') },
  { id: 23,  name: 'Gents Ring', code: 'GR-1050', category: 'rings', image: gd('1sM2RavtJWZhzyPh4D5-dV3Lxupg-r4p1') },
  { id: 24,  name: 'Gents Ring', code: 'GR-1051', category: 'rings', image: gd('1sAxp5B2i_jYjtz_nFtuPr29sLHoUTw1s') },
  { id: 25,  name: 'Gents Ring', code: 'GR-1052', category: 'rings', image: gd('1Yt_RXWNr0QvVbbdL3-sO_TMLxRE73QOn') },
  { id: 26,  name: 'Gents Ring', code: 'GR-1053', category: 'rings', image: gd('1RgrqE-UjYPoZjh1tQoIzA7A_CYD6eIIt') },
  { id: 27,  name: 'Gents Ring', code: 'GR-1054', category: 'rings', image: gd('1ujjnCZPp_rYrAAfGtx4j6-s7dLIGCJfd') },
  { id: 28,  name: 'Gents Ring', code: 'GR-1055', category: 'rings', image: gd('1mskhC9QLC34mQxjLS1uAn-4KyDp-puMw') },
  { id: 29,  name: 'Gents Ring', code: 'GR-1056', category: 'rings', image: gd('1fw4ERzdNGLBtOWaq8wP6KvAyrg-t9cqb') },
  { id: 30,  name: 'Gents Ring', code: 'GR-1057', category: 'rings', image: gd('1XYMTebZWySWmSQ4HRsdacYIlZ2wBSKZE') },
  { id: 31,  name: 'Gents Ring', code: 'GR-1058', category: 'rings', image: gd('1ks6yy0sKl2a3A6HgsWCVoSD4jfEEF4ik') },
  { id: 32,  name: 'Gents Ring', code: 'GR-1059', category: 'rings', image: gd('1APkEPYJAZIo3Bx2psu8-wzKvefdS7u1h') },
  { id: 33,  name: 'Gents Ring', code: 'GR-1060', category: 'rings', image: gd('1ze6OtZ1cmn57LoRFJG8P7bxh2iBr2g5t') },
  { id: 34,  name: 'Gents Ring', code: 'GR-1061', category: 'rings', image: gd('1j5KButwBd039A-cMpezLejAkgOBV0NLn') },
  { id: 35,  name: 'Gents Ring', code: 'GR-1062', category: 'rings', image: gd('1pgdhEln5HEn-MmxMLRQT4dC2omoBohl7') },
  { id: 36,  name: 'Gents Ring', code: 'GR-1063', category: 'rings', image: gd('1tjKhTDtbSvrt15LFJh33vv0d938Yl4lP') },
  { id: 37,  name: 'Gents Ring', code: 'GR-1064', category: 'rings', image: gd('1-zGf0BicbbhzBkcHazCBc1W-2hOrmiuc') },
  { id: 38,  name: 'Gents Ring', code: 'GR-1065', category: 'rings', image: gd('1LwQpixokv7ohz5IQWn-jGKI4Jf-uYqRL') },
  { id: 39,  name: 'Gents Ring', code: 'GR-1066', category: 'rings', image: gd('1zGSWB4r729VVaLHrT5BqWxx_CtwElbsS') },
  { id: 40,  name: 'Gents Ring', code: 'GR-1067', category: 'rings', image: gd('1m9jlPHQjl8G5R27phA1CdmaIbhV_NAIA') },
  { id: 41,  name: 'Gents Ring', code: 'GR-1068', category: 'rings', image: gd('1Fo6AlLjy-GssM2T3W1E_EcWvdrq2xhIO') },
  { id: 42,  name: 'Gents Ring', code: 'GR-1069', category: 'rings', image: gd('1N85vunmNWzvTAXMApejJk5VFXd8Rq7bt') },
  { id: 43,  name: 'Gents Ring', code: 'GR-1070', category: 'rings', image: gd('1oneiS-qJow2Wf7c-9BeNksFpTCsZKOCs') },
  { id: 44,  name: 'Gents Ring', code: 'GR-1071', category: 'rings', image: gd('1_vHf_XoNKrXoF687TIFGMTRLgl1GNPyk') },
  { id: 45,  name: 'Gents Ring', code: 'GR-1072', category: 'rings', image: gd('143SjEdhhQhhWOkvDhjGyheDtek660o3T') },
  { id: 46,  name: 'Gents Ring', code: 'GR-1073', category: 'rings', image: gd('1QX8RUcBZmrJF5xXHqBR1Ewx_hW2O_eji') },
  { id: 47,  name: 'Gents Ring', code: 'GR-1074', category: 'rings', image: gd('1u1gfN67pbll84eo52iDbDdnwKIJ1aQ6T') },
  { id: 48,  name: 'Gents Ring', code: 'GR-1075', category: 'rings', image: gd('1WB6SuRYz72hRthCh6Ybr6Q7Ve_AIshUp') },
  { id: 49,  name: 'Gents Ring', code: 'GR-1076', category: 'rings', image: gd('1tLcSQC9mho_YMx_56Y7MGPqRauAEtZvP') },
  { id: 50,  name: 'Gents Ring', code: 'GR-1077', category: 'rings', image: gd('1hpDFoGJ1U0k7xwTpHvfaR5W00tAY1p9U') },

  // ── Earrings (ER) ────────────────────────────────────────────────────────
  { id: 51,  name: 'Earring', code: 'ER-1023', category: 'earrings', image: gd('1Kzyc1wM1M9xN8S__IoM6x2SV0KWOaQOb') },
  { id: 52,  name: 'Earring', code: 'ER-1024', category: 'earrings', image: gd('1GSXF5WNyIrdxdjLNIZfvdzx29pkiIrQU') },
  { id: 53,  name: 'Earring', code: 'ER-1025', category: 'earrings', image: gd('1ya01s6C6PZWa2nvl4CoEPXLUsrIlQv25') },
  { id: 54,  name: 'Earring', code: 'ER-1026', category: 'earrings', image: gd('17JRXQfEfnw5jWSJlxewHPnfqfShj7T7s') },
  { id: 55,  name: 'Earring', code: 'ER-1027', category: 'earrings', image: gd('1CBBZjK41YK2W_gPX5eIlBou6-CR4OcaV') },
  { id: 56,  name: 'Earring', code: 'ER-1028', category: 'earrings', image: gd('117f-TI_J-49akPPgQsbVjR-UXi_g1srk') },
  { id: 57,  name: 'Earring', code: 'ER-1029', category: 'earrings', image: gd('1q8v_ADXSZcjgZN9s7K3s6rcUodV2NQ5m') },
  { id: 58,  name: 'Earring', code: 'ER-1030', category: 'earrings', image: gd('197DtJnkNrRCNVGsfJSOhjbC23a18GIxR') },
  { id: 59,  name: 'Earring', code: 'ER-1031', category: 'earrings', image: gd('1ez9xnx3SZi2Us78jE1OHfrEjrPyuZoki') },
  { id: 60,  name: 'Earring', code: 'ER-1032', category: 'earrings', image: gd('1K1NBfv3mhz7cThPlu95zAzAjW3-K6lpN') },
  { id: 61,  name: 'Earring', code: 'ER-1033', category: 'earrings', image: gd('1yq7dXWtYTelfPN0_LoTEHmQcXpDv4hL3') },
  { id: 62,  name: 'Earring', code: 'ER-1034', category: 'earrings', image: gd('1oKLaGeojaEETq4GakTcAjxdVaHBHMx9j') },
  { id: 63,  name: 'Earring', code: 'ER-1035', category: 'earrings', image: gd('1Vl9yc5GbBMR3NddwhQOWUe7au47YfhRV') },
  { id: 64,  name: 'Earring', code: 'ER-1036', category: 'earrings', image: gd('1WqjfJtWAzfPYVlylre0NKGs_AKpNk7ch') },
  { id: 65,  name: 'Earring', code: 'ER-1037', category: 'earrings', image: gd('10LjrYau_yj2kzmtka9C2BjxdFYK836b2') },
  { id: 66,  name: 'Earring', code: 'ER-1038', category: 'earrings', image: gd('1_fONZ0mLIiW5xqGRSsI-a_WJ30TPvcuE') },
  { id: 67,  name: 'Earring', code: 'ER-1039', category: 'earrings', image: gd('1h3g43Bkcqg2K22Wa8s43U52OLPcevH_3') },
  { id: 68,  name: 'Earring', code: 'ER-1040', category: 'earrings', image: gd('1ZxTH5IrMCPkbmZqx9pSoRJMHjNJqZpCq') },
  { id: 69,  name: 'Earring', code: 'ER-1041', category: 'earrings', image: gd('1sAas9F3yW8r4BP1O6pzePgEz2R3E8JCA') },
  { id: 70,  name: 'Earring', code: 'ER-1042', category: 'earrings', image: gd('1C9xgWnUBx3-sGmqFfYxavkMFGzI-xCA2') },
  { id: 71,  name: 'Earring', code: 'ER-1043', category: 'earrings', image: gd('1JE5RWR7h2ZZVt5kT5waS4FP_v9ZDI3-2') },
  { id: 72,  name: 'Earring', code: 'ER-1044', category: 'earrings', image: gd('1ewUqjdn_37RlTvPJ87V9lsBg5bPFAKbg') },
  { id: 73,  name: 'Earring', code: 'ER-1045', category: 'earrings', image: gd('103MrN0pJVgcQ5OZBdHseeS4-0tE6_G6W') },
  { id: 74,  name: 'Earring', code: 'ER-1046', category: 'earrings', image: gd('1Cg4AfwFlKH-45uCaXMMIGHpQnIb_acjr') },
  { id: 75,  name: 'Earring', code: 'ER-1047', category: 'earrings', image: gd('1hR4V_G1eo4P2nLQzG5Reg8wxlMVgnVMf') },
  { id: 76,  name: 'Earring', code: 'ER-1048', category: 'earrings', image: gd('1x7F6MVpgIjEEtgVhgNs8j7nF1XqDjhJa') },
  { id: 77,  name: 'Earring', code: 'ER-1049', category: 'earrings', image: gd('1fQgHY04QL4K5zhc3nsAtk91y7dYyouCA') },
  { id: 78,  name: 'Earring', code: 'ER-1050', category: 'earrings', image: gd('1G0b2qu7zg6osE9h5KriWZSyuIt8B647_') },
  { id: 79,  name: 'Earring', code: 'ER-1052', category: 'earrings', image: gd('1MBSvlcaHKIRClPdT95JWkvJF7YP0WISo') },
  { id: 80,  name: 'Earring', code: 'ER-1053', category: 'earrings', image: gd('1NLMMqpcx44E1ZOjtXRnc85S-nRZcK6Tm') },

  // ── Bangles (BL) ─────────────────────────────────────────────────────────
  { id: 81,  name: 'Bangle', code: 'BL-1000', category: 'bangles', image: gd('1R0ApB1xwabmOTnU5JggNhmsAzsjvNIrx') },
  { id: 82,  name: 'Bangle', code: 'BL-1001', category: 'bangles', image: gd('1RL-Z1XPYLznJUrJvybLVUXTV1RIiK_eL') },
  { id: 83,  name: 'Bangle', code: 'BL-1002', category: 'bangles', image: gd('1kPnTYqsBugLSNkxl8lW5vU-yHtl71kmn') },
  { id: 84,  name: 'Bangle', code: 'BL-1003', category: 'bangles', image: gd('1hYXzcGag5noSAQPPoCCbqS3nUiNDCVrj') },
  { id: 85,  name: 'Bangle', code: 'BL-1005', category: 'bangles', image: gd('13AUY2ccPROUMJsAIwBTrEvh9vnIbAOIA') },
  { id: 86,  name: 'Bangle', code: 'BL-1019', category: 'bangles', image: gd('1BVNRaeIzul7yJB65uGxsgfrYI10IEIRh') },
  { id: 87,  name: 'Bangle', code: 'BL-1034', category: 'bangles', image: gd('1VRLHnod7khMkGPlDkKS5MF9E5q4DVH5U') },
  { id: 88,  name: 'Bangle', code: 'BL-1035', category: 'bangles', image: gd('1UY3qogH9US-yOZnpcx9xx2ACq_-oZU7w') },
  { id: 89,  name: 'Bangle', code: 'BL-1036', category: 'bangles', image: gd('15O_uHQYgZhliMxRjxgTwbtlKfEcKdfm9') },
  { id: 90,  name: 'Bangle', code: 'BL-1037', category: 'bangles', image: gd('1sjIJ3hBWcHFsA09Pp8mEEXvUKoSsy8UJ') },

  // ── Necklaces (NCK) ───────────────────────────────────────────────────────
  { id: 91,  name: 'Necklace', code: 'NCK-1001', category: 'necklaces', image: gd('1zDxCMeN6Z0U_ajCC0xlkS3-zG1g-Z7JF') },
  { id: 92,  name: 'Necklace', code: 'NCK-1002', category: 'necklaces', image: gd('1lDDatIN36ku8oFKcYW-VY4CA3thUDg5W') },
  { id: 93,  name: 'Necklace', code: 'NCK-1003', category: 'necklaces', image: gd('1EORCZXvakbPum_mEFzz4GpxagYooUBzj') },
  { id: 94,  name: 'Necklace', code: 'NCK-1004', category: 'necklaces', image: gd('1kUVotuOWbW7ENzL7w-honAc9AjdBOxdY') },
  { id: 95,  name: 'Necklace', code: 'NCK-1005', category: 'necklaces', image: gd('1O2-nUpJKqRCNkxsJedX9GHCNfLSaiEJk') },
  { id: 96,  name: 'Necklace', code: 'NCK-1006', category: 'necklaces', image: gd('1c_qqdwfh83s6hvNO7M7uTIokXya8Osz9') },
  { id: 97,  name: 'Necklace', code: 'NCK-1007', category: 'necklaces', image: gd('1fDiD7oS0PG0QBIac5dvGLhlB4XrPw5cR') },

  // ── Pendants (PD) ────────────────────────────────────────────────────────
  { id: 98,  name: 'Pendant', code: 'PD-1142', category: 'pendants', image: gd('1GipI72lddGuoZaMT0RwIOyTx98WUVKm8') },
  { id: 99,  name: 'Pendant', code: 'PD-1145', category: 'pendants', image: gd('1i4zKB212COMS8UPc9fJ9anW6a6Hw5FgS') },
  { id: 100, name: 'Pendant', code: 'PD-1146', category: 'pendants', image: gd('1SF5aj1HUqkcZdeF05IwqvpSE_ZD7KwZH') },
  { id: 101, name: 'Pendant', code: 'PD-1147', category: 'pendants', image: gd('1aw3GaYKo6OlxQduLFR7NsFAP3h4vyy2P') },
  { id: 102, name: 'Pendant', code: 'PD-1148', category: 'pendants', image: gd('1QEJCrfm7mvDsIGmLTCu25BGak1s8H_H8') },
  { id: 103, name: 'Pendant', code: 'PD-1149', category: 'pendants', image: gd('1Bwzgrk16KB8ty9zf5C2Kp3OC-38O2z_u') },
  { id: 104, name: 'Pendant', code: 'PD-1150', category: 'pendants', image: gd('1iJurpWDBbmCmy19D7_BwKAXd_1NIMBlN') },
  { id: 105, name: 'Pendant', code: 'PD-1151', category: 'pendants', image: gd('1Qf69Xn6AKqVfQX8A8pLBh3cheQq6P_AJ') },
  { id: 106, name: 'Pendant', code: 'PD-1152', category: 'pendants', image: gd('149W5zDdDL3K9Oh4i-5xM4P-s8flTdH2V') },
  { id: 107, name: 'Pendant', code: 'PD-1153', category: 'pendants', image: gd('1m3HYankt3yscal9jPFfLek-yJcsY-JEr') },

  // ── Tops (T) ─────────────────────────────────────────────────────────────
  { id: 108, name: 'Tops', code: 'T-1003', category: 'tops', image: gd('1fbYYis9FFEyDae22NSJw4dDXivSFGbve') },
  { id: 109, name: 'Tops', code: 'T-1004', category: 'tops', image: gd('1X0AyJBrVc90p7AKjH7a05m2nkN8JJ4qR') },
  { id: 110, name: 'Tops', code: 'T-1005', category: 'tops', image: gd('1ZP4sb1Wn4uHuhHDgCmvMe9ZXDz0-k4r3') },
  { id: 111, name: 'Tops', code: 'T-1006', category: 'tops', image: gd('1V84LVhmv7jTW-Wp_6G7nl2obkRPKOHth') },
  { id: 112, name: 'Tops', code: 'T-1007', category: 'tops', image: gd('1bOeY9VRKT5HzffDtS7RHREDw5-eKIOG6') },
  { id: 113, name: 'Tops', code: 'T-1008', category: 'tops', image: gd('1BJ2yU17TAToKfeIKAPniSL59nQNO8BnP') },
  { id: 114, name: 'Tops', code: 'T-1009', category: 'tops', image: gd('1e2OJ1vUo1NZf4ePPCRAKtaWWBfweYOpx') },
  { id: 115, name: 'Tops', code: 'T-1010', category: 'tops', image: gd('1gZCPfEczqIWqx-m86lbf3Xx6pTRqI_gx') },
  { id: 116, name: 'Tops', code: 'T-1011', category: 'tops', image: gd('1Tg81Qx8_XeroCiYMxV0GhR1No7TDWSlc') },
  { id: 117, name: 'Tops', code: 'T-1012', category: 'tops', image: gd('1KmGePthi1ziu06L9T50v3oB8oftCJ7kn') },

  // ── Bracelets (GBR) ──────────────────────────────────────────────────────
  { id: 118, name: 'Bracelet', code: 'GBR-1001', category: 'bracelets', image: gd('1sYqEJnPk5b-VFJ991bjGszUqkg_No8YJ') },
  { id: 119, name: 'Bracelet', code: 'GBR-1002', category: 'bracelets', image: gd('12F3CGF-SY4BKsaS2IbKAxl9ZPmiac5cg') },
  { id: 120, name: 'Bracelet', code: 'GBR-1003', category: 'bracelets', image: gd('1NG2D573mNMGgKNnqjffX7e8d1cGmvXC0') },
  { id: 121, name: 'Bracelet', code: 'GBR-1004', category: 'bracelets', image: gd('1iyK_6CB288IxsPgeJRga5fKMgtzub6f4') },
  { id: 122, name: 'Bracelet', code: 'GBR-1005', category: 'bracelets', image: gd('1HK08Y9lvgfxIB1VxYndbUtdXhqS1_x6V') },

  // ── Nose Pin ─────────────────────────────────────────────────────────────
  { id: 123, name: 'Nose Pin', code: 'NP-154', category: 'nosepin', image: gd('14QDpfIvU-z0xju_3NfX_XQ6eCqWSX0dU') },
  { id: 124, name: 'Nose Pin', code: 'NP-155', category: 'nosepin', image: gd('1K9q9nJpG5Wzya1P6zA73cgfPh6QXsNJs') },
  { id: 125, name: 'Nose Pin', code: 'NP-156', category: 'nosepin', image: gd('170g19TEnwye_tFWk7MAXRH99RsaTxM6p') },
  { id: 126, name: 'Nose Pin', code: 'NP-157', category: 'nosepin', image: gd('17AeqorrUYSm3haG460r4IxctwQVDvUuQ') },
  { id: 127, name: 'Nose Pin', code: 'NP-158', category: 'nosepin', image: gd('1glNVCfF0KQy6B-jz7T-YBQJM5A8kpWst') },

  // ── Ladies Ring (LR) ─────────────────────────────────────────────────────
  { id: 128, name: 'Ladies Ring', code: 'LR-1118', category: 'ladiesring', image: gd('1YMMvDwwnsAXAnnop4KeWidzV6OZmnVap') },
  { id: 129, name: 'Ladies Ring', code: 'LR-1164', category: 'ladiesring', image: gd('1W-T02ZySwgatSwKYv-tZH4VnFFiSZui0') },
  { id: 130, name: 'Ladies Ring', code: 'LR-1196', category: 'ladiesring', image: gd('12j-g_UJg8M38HCMywV98aauU9iuSIIVT') },
  { id: 131, name: 'Ladies Ring', code: 'LR-1475', category: 'ladiesring', image: gd('1NCS0-Iswwe2pxTkFeS3z_4rhb-UXAkVb') },
  { id: 132, name: 'Ladies Ring', code: 'LR-1476', category: 'ladiesring', image: gd('1Wvx3rzHTjjg8V6hH5ydUDNTgyIVGAeGI') },
  { id: 133, name: 'Ladies Ring', code: 'LR-1477', category: 'ladiesring', image: gd('1z2PL-84KTpUcez-_agJdgC-_RgVr13i0') },
  { id: 134, name: 'Ladies Ring', code: 'LR-1478', category: 'ladiesring', image: gd('1YNHmXCsQLNaLLf9oxLI0U3R_cgTC4LFG') },
  { id: 135, name: 'Ladies Ring', code: 'LR-1479', category: 'ladiesring', image: gd('10iagp8UUmrAcEgWuw7H9ZlG8v0m8OwFt') },
  { id: 136, name: 'Ladies Ring', code: 'LR-1480', category: 'ladiesring', image: gd('1kg7JeUlQN4L0TSf_Dwj7n0LtQ2OlW5uv') },
  { id: 137, name: 'Ladies Ring', code: 'LR-1481', category: 'ladiesring', image: gd('1SywOxphswzrpcHpcGcWgkZBhGWLbMJar') },
  { id: 138, name: 'Ladies Ring', code: 'LR-1482', category: 'ladiesring', image: gd('1qwbepbfhXGOAspFoFO3kO9sgeDw9u3vj') },
  { id: 139, name: 'Ladies Ring', code: 'LR-1483', category: 'ladiesring', image: gd('1Frdr1-3pmg21C5F_bbXxQ7HB-5xGrwsA') },
  { id: 140, name: 'Ladies Ring', code: 'LR-1484', category: 'ladiesring', image: gd('1wlDI9hOxL5lknf6x7yx2nZPhWaDp4vMN') },
  { id: 141, name: 'Ladies Ring', code: 'LR-1485', category: 'ladiesring', image: gd('1RmSm708qPbjzBUsDFRNhT-trWq9fPrin') },
  { id: 142, name: 'Ladies Ring', code: 'LR-1486', category: 'ladiesring', image: gd('14j3SoMac9x1kDap_1y8-OLa8uEZN7-T2') },
  { id: 143, name: 'Ladies Ring', code: 'LR-1487', category: 'ladiesring', image: gd('1JIyWeUlkn8lR3a48XbKGWi5Chwhe9LZX') },
  { id: 144, name: 'Ladies Ring', code: 'LR-1488', category: 'ladiesring', image: gd('1c3TJUokJu97UZFe2NUGIixmgoUyMLSaj') },
  { id: 145, name: 'Ladies Ring', code: 'LR-1489', category: 'ladiesring', image: gd('1zQ83HJRHcJDcxMdVixujg1fW1Y0BXMxc') },
  { id: 146, name: 'Ladies Ring', code: 'LR-1490', category: 'ladiesring', image: gd('10az4avV3IUdyl4T38yoDceiOiKGoM9vP') },
  { id: 147, name: 'Ladies Ring', code: 'LR-1491', category: 'ladiesring', image: gd('15R56exaYTMVgrb3VfkH_S7D5qheYZgy7') },
  { id: 148, name: 'Ladies Ring', code: 'LR-1492', category: 'ladiesring', image: gd('1r3-PThna4Pmnesw3HpwHanq-Q24Yc6dA') },
  { id: 149, name: 'Ladies Ring', code: 'LR-1493', category: 'ladiesring', image: gd('1wjwEaeCHElFaMP8Td_MTQ5r6BfSWHN_k') },
  { id: 150, name: 'Ladies Ring', code: 'LR-1494', category: 'ladiesring', image: gd('17tO4mSYNGXNuhN-R-o7ouYiOqfx2jYad') },
  { id: 151, name: 'Ladies Ring', code: 'LR-1495', category: 'ladiesring', image: gd('1PbfnTp_FPAPxW3p4yDBaELz42M0n8tam') },
  { id: 152, name: 'Ladies Ring', code: 'LR-1496', category: 'ladiesring', image: gd('1WenJin5kKugCy98_lEPXADGQMHsd18Qu') },
  { id: 153, name: 'Ladies Ring', code: 'LR-1497', category: 'ladiesring', image: gd('1PyBS_c-UK1CA2bFK_Iq8S6I-p4SIdckc') },
  { id: 154, name: 'Ladies Ring', code: 'LR-1498', category: 'ladiesring', image: gd('1bF-vMHs9oSEgVCPdZ5fVbNOguHABr5VC') },
  { id: 155, name: 'Ladies Ring', code: 'LR-1499', category: 'ladiesring', image: gd('1BelSzYIH5Z2DYc6UMXt8jge3QS0sPmZ0') },
  { id: 156, name: 'Ladies Ring', code: 'LR-1500', category: 'ladiesring', image: gd('1B76AB-QOXSX1nM4r7jHS2UgoN4Ma-ha_') },
  { id: 157, name: 'Ladies Ring', code: 'LR-1501', category: 'ladiesring', image: gd('1ZgS_8cATuZI_g-4XnwiWupj8wCNCIhqg') },
  { id: 158, name: 'Ladies Ring', code: 'LR-1502', category: 'ladiesring', image: gd('1yDKXiWXfeFOrlmi5TIN-w5TJ78vmefop') },
  { id: 159, name: 'Ladies Ring', code: 'LR-1503', category: 'ladiesring', image: gd('1VAWIXG0k4Hg6ezpyx-l3IrUIJtjefkxn') },
  { id: 160, name: 'Ladies Ring', code: 'LR-1504', category: 'ladiesring', image: gd('1C67NGcEn3KoK4RkShu23pfuaAB0QGJnj') },
  { id: 161, name: 'Ladies Ring', code: 'LR-1505', category: 'ladiesring', image: gd('1NiuJqdn8uADAMoTPgRVrrWcc4ptb5fUO') },
  { id: 162, name: 'Ladies Ring', code: 'LR-1506', category: 'ladiesring', image: gd('1HnJhUNVRB4E89pcrgDT9tzsPjlwhEY_W') },
  { id: 163, name: 'Ladies Ring', code: 'LR-1507', category: 'ladiesring', image: gd('1XcdD5qsGttTqlZgziZMNBJa-637QMWIv') },
  { id: 164, name: 'Ladies Ring', code: 'LR-1508', category: 'ladiesring', image: gd('1r3QY5Ll357-GcDCbOoWo5_5caUeGhtLB') },
  { id: 165, name: 'Ladies Ring', code: 'LR-1509', category: 'ladiesring', image: gd('1dLnwJttddhdRkuJHRXHmr3qzhn5OAwRK') },
  { id: 166, name: 'Ladies Ring', code: 'LR-1510', category: 'ladiesring', image: gd('1kVeZY-4Zokyg9iQz_QSdhe3mvOD1ckId') },
  { id: 167, name: 'Ladies Ring', code: 'LR-1511', category: 'ladiesring', image: gd('1Pcyef1qBD3IfueGqn_bOap9P4LfzF1te') },
  { id: 168, name: 'Ladies Ring', code: 'LR-1512', category: 'ladiesring', image: gd('1C6bAK-lpHtLGavV0qUVoycxYF7jsJ5cL') },
  { id: 169, name: 'Ladies Ring', code: 'LR-1513', category: 'ladiesring', image: gd('1axNnANZ5puvq6OoCIZrE1D3DEoVt-wwG') },
  { id: 170, name: 'Ladies Ring', code: 'LR-1514', category: 'ladiesring', image: gd('1QyFXu0P7_4GrB3pMpaeeclzFiiQLwipz') },
  { id: 171, name: 'Ladies Ring', code: 'LR-1515', category: 'ladiesring', image: gd('1pyKb0F9vYO8tclA-T_AnpaUwq30xY_AR') },
  { id: 172, name: 'Ladies Ring', code: 'LR-1516', category: 'ladiesring', image: gd('1ZSbFaiiyYnAyYgWHUvOa_IUT9t3pzW3-') },
  { id: 173, name: 'Ladies Ring', code: 'LR-1517', category: 'ladiesring', image: gd('16z40dq6yC339Kl8e92cczg1bJmCXXO09') },
  { id: 174, name: 'Ladies Ring', code: 'LR-1518', category: 'ladiesring', image: gd('1UOgx5QlW0tl4cE9vXH-Au2oj1DIiVxOK') },
  { id: 175, name: 'Ladies Ring', code: 'LR-1519', category: 'ladiesring', image: gd('1O9lS36nfE2LZICSdFIkIPu8gCoaTeJVH') },
  { id: 176, name: 'Ladies Ring', code: 'LR-1520', category: 'ladiesring', image: gd('1_IjNy9mt_-qRk5YUDW8ftqtJSDYjn749') },
  { id: 177, name: 'Ladies Ring', code: 'LR-1521', category: 'ladiesring', image: gd('1MgEnHQZdnhr3XkCJi0SJCGqy43Dt7I1D') },

  // ── Ladies Bangles (LB) ───────────────────────────────────────────────────
  { id: 178, name: 'Ladies Bangle', code: 'LB-1000', category: 'ladiesbangles', image: gd('1JUe96OyClj31z5WpbdLaD09SXGtFrQc1') },
  { id: 179, name: 'Ladies Bangle', code: 'LB-1001', category: 'ladiesbangles', image: gd('1baPsomFH-5iFndkFnXzyZbBHODKjAYdX') },
  { id: 180, name: 'Ladies Bangle', code: 'LB-1002', category: 'ladiesbangles', image: gd('1pSGl87oQqopcx1R4azmfT2afPix-_13k') },
  { id: 181, name: 'Ladies Bangle', code: 'LB-1003', category: 'ladiesbangles', image: gd('1yi7aBrTvMtGNjAfp4FWTorNubw7T11Kt') },
  { id: 182, name: 'Ladies Bangle', code: 'LB-1004', category: 'ladiesbangles', image: gd('12Q4b40mC61pPgcFZcoJXuv8ajKwomhcl') },
  { id: 183, name: 'Ladies Bangle', code: 'LB-1071', category: 'ladiesbangles', image: gd('1Wtx1-M7ev8NvuYf8FC6UWzk97aV0BImH') },
  { id: 184, name: 'Ladies Bangle', code: 'LB-1074', category: 'ladiesbangles', image: gd('1-jz6eTq3oa4ss-K7MCcL50mt78rjCcWq') },
  { id: 185, name: 'Ladies Bangle', code: 'LB-1075', category: 'ladiesbangles', image: gd('1baoKz3lFgqfYEoeCJ4QyPSc3kCLzFyIZ') },
  { id: 186, name: 'Ladies Bangle', code: 'LB-1076', category: 'ladiesbangles', image: gd('1926-NORL8t3UDYAZkLpWjXyYDKg8j0mk') },
  { id: 187, name: 'Ladies Bangle', code: 'LB-1077', category: 'ladiesbangles', image: gd('1ap3KD2GzFEVpxkVM52L1cFqIyHxaNAF4') },
  { id: 188, name: 'Ladies Bangle', code: 'LB-1078', category: 'ladiesbangles', image: gd('1hrkEG7Ip7bcyEh0U2a-T6WFKGVC9tfLl') },
  { id: 189, name: 'Ladies Bangle', code: 'LB-1079', category: 'ladiesbangles', image: gd('1Wwp82YANfwaXlqFUl6sDZFgHv43qXGXv') },
  { id: 190, name: 'Ladies Bangle', code: 'LB-1080', category: 'ladiesbangles', image: gd('1RRNxdmhY0CqFb3v2LVSG-vAtchKkGbRA') },
  { id: 191, name: 'Ladies Bangle', code: 'LB-1081', category: 'ladiesbangles', image: gd('18F7_fpil1-GBhrsya8TxsiGV-XSYpbLC') },
  { id: 192, name: 'Ladies Bangle', code: 'LB-1082', category: 'ladiesbangles', image: gd('1E4ZWkqZUIT_53d2iHfJwfyWtA7kfKgl3') },
  { id: 193, name: 'Ladies Bangle', code: 'LB-1083', category: 'ladiesbangles', image: gd('1jYls8AG1LzJHy-NrDSP4yfV4ROTvLqqx') },
  { id: 194, name: 'Ladies Bangle', code: 'LB-1084', category: 'ladiesbangles', image: gd('1QRPTxwo2tGwk3Dc_RAUYNUoD_wY2Ka5e') },
  { id: 195, name: 'Ladies Bangle', code: 'LB-1085', category: 'ladiesbangles', image: gd('10s5scpSGj4s7yhAsziweR7B2Ew5qf9f_') },
  { id: 196, name: 'Ladies Bangle', code: 'LB-1086', category: 'ladiesbangles', image: gd('1un6XsPKD6e9e2CsH9EiSRj3oYbyP_W1A') },
  { id: 197, name: 'Ladies Bangle', code: 'LB-1087', category: 'ladiesbangles', image: gd('1r-ygY8OfURawOnPu0YYWalsf2BrdSyy7') },
  { id: 198, name: 'Ladies Bangle', code: 'LB-1088', category: 'ladiesbangles', image: gd('1mxMtXqN1-2__qWQCpBF6XTKdwj0UfWSo') },
  { id: 199, name: 'Ladies Bangle', code: 'LB-1089', category: 'ladiesbangles', image: gd('1xLRdO4xXd9ju4RLwSuzBNwMz_ooU3LP1') },
  { id: 200, name: 'Ladies Bangle', code: 'LB-1090', category: 'ladiesbangles', image: gd('1zsf3Ak51NeJizMM0mt8JbXWbMJLglOyf') },
  { id: 201, name: 'Ladies Bangle', code: 'LB-1091', category: 'ladiesbangles', image: gd('1tsByl8Yk4zwdCc6eVFF5Mno-k_cBCbqd') },
  { id: 202, name: 'Ladies Bangle', code: 'LB-1092', category: 'ladiesbangles', image: gd('1fqmq58Rgx9AjZAt42L-ZfAiaRd4L4n1S') },
  { id: 203, name: 'Ladies Bangle', code: 'LB-1093', category: 'ladiesbangles', image: gd('1dHiNMRGYEQ-WMmT9ey_WWEzhPY7Arip_') },
  { id: 204, name: 'Ladies Bangle', code: 'LB-1094', category: 'ladiesbangles', image: gd('1xm4yOAccPXubOo5_Cqhmnudbt4jnqIMQ') },
  { id: 205, name: 'Ladies Bangle', code: 'LB-1095', category: 'ladiesbangles', image: gd('1Sg72RGwHtNsnSc4qU6hC6T_1Ir6RXFUR') },
  { id: 206, name: 'Ladies Bangle', code: 'LB-1096', category: 'ladiesbangles', image: gd('1nEv1aJ6VDIez7pv2NPSKBxzULMtxpFWW') },
  { id: 207, name: 'Ladies Bangle', code: 'LB-1097', category: 'ladiesbangles', image: gd('14r-oyWdIW_DxhYaZGQpu215VrhxSLE_e') },
  { id: 208, name: 'Ladies Bangle', code: 'LB-1098', category: 'ladiesbangles', image: gd('1S6z95YWKf8keB03_nBL0hyNxbHWmTgYm') },
  { id: 209, name: 'Ladies Bangle', code: 'LB-1099', category: 'ladiesbangles', image: gd('1tdItOKKUPYLVQj386pvb7H1uwEUy6sTS') },
  { id: 210, name: 'Ladies Bangle', code: 'LB-1100', category: 'ladiesbangles', image: gd('1APsDlMgt_J_KPNp6vXkcSJuySr02sPHw') },
  { id: 211, name: 'Ladies Bangle', code: 'LB-1101', category: 'ladiesbangles', image: gd('1Jojk-VyuXewDwhEeWOhRM6czFKEK6ffv') },
  { id: 212, name: 'Ladies Bangle', code: 'LB-1102', category: 'ladiesbangles', image: gd('1km9O1bRRkBBhj9Gh7e92bI46vhlEFDyB') },
  { id: 213, name: 'Ladies Bangle', code: 'LB-1103', category: 'ladiesbangles', image: gd('1Lit5jkkOMnVcmypXGne6O7aD2DFr02Yr') },
  { id: 214, name: 'Ladies Bangle', code: 'LB-1104', category: 'ladiesbangles', image: gd('1SSVR94BZsrKX9GgINGk-o5XwtESo7YLT') },
  { id: 215, name: 'Ladies Bangle', code: 'LB-1105', category: 'ladiesbangles', image: gd('1v8v-L_oCH5D2Hd-rLfdQZRViIcvqYIk7') },
  { id: 216, name: 'Ladies Bangle', code: 'LB-1106', category: 'ladiesbangles', image: gd('1mo9pB7NO7Rbb96ncheQ4qL8cWrEHRuEX') },
  { id: 217, name: 'Ladies Bangle', code: 'LB-1107', category: 'ladiesbangles', image: gd('17PMj_jbUD7P1cYFPjVptjiNEk8zWt0Kv') },
  { id: 218, name: 'Ladies Bangle', code: 'LB-1108', category: 'ladiesbangles', image: gd('1iFI6k2AnlgmfTeooJRuW6f7BnJ_tXTRb') },
  { id: 219, name: 'Ladies Bangle', code: 'LB-1109', category: 'ladiesbangles', image: gd('1Zry3kENcEb7t9438er8Cfk0lpiQw_SI4') },
  { id: 220, name: 'Ladies Bangle', code: 'LB-1110', category: 'ladiesbangles', image: gd('1PyiGYoyM4LCzmEMBPFz0yioim4kQBSNH') },
  { id: 221, name: 'Ladies Bangle', code: 'LB-1111', category: 'ladiesbangles', image: gd('1gJBogR3mZPeM6TThreHE1AD-CC7QxYCs') },
  { id: 222, name: 'Ladies Bangle', code: 'LB-1112', category: 'ladiesbangles', image: gd('1N7NYuO7hb6YQ2TpwNNxRBew3HU03ygq6') },
  { id: 223, name: 'Ladies Bangle', code: 'LB-1113', category: 'ladiesbangles', image: gd('1aCeBc0FI1wlETZ-eHbrUJeZDY5grehFW') },
  { id: 224, name: 'Ladies Bangle', code: 'LB-1114', category: 'ladiesbangles', image: gd('1tP94IrbDXwjy9ld3bSQP0CARk3xc457P') },
  { id: 225, name: 'Ladies Bangle', code: 'LB-1115', category: 'ladiesbangles', image: gd('1cGfDbB4H_IJQaOg4tlagMrePffcKVSJv') },
  { id: 226, name: 'Ladies Bangle', code: 'LB-1116', category: 'ladiesbangles', image: gd('10ST-6lGzZThiXWSc9XzlBxD1q9AHzeue') },
  { id: 227, name: 'Ladies Bangle', code: 'LB-1117', category: 'ladiesbangles', image: gd('1HUg2CeUVoMdZaM-ZbTp1DhN5tq_rL4cd') },

  // ── Pendant Set (PS) ─────────────────────────────────────────────────────
  { id: 228, name: 'Pendant Set', code: 'PS-P-1000', category: 'pendantset', image: gd('1z3tj2AjkmjO0ERBLxwgEQ3W6do8GhZrG') },
  { id: 229, name: 'Pendant Set', code: 'PS-P-1001', category: 'pendantset', image: gd('1RGQpFv0Bzhhvf5CoAZGBaQZYSkDf6Jgn') },
  { id: 230, name: 'Pendant Set', code: 'PS-P-1002', category: 'pendantset', image: gd('1Ol7_5RQUZnfrJXKeWj16Ac_WwIWOWDIC') },
  { id: 231, name: 'Pendant Set', code: 'PS-P-1003', category: 'pendantset', image: gd('1wCefOSWUxCVa4pUFRIcAbV72XEi9503A') },
  { id: 232, name: 'Pendant Set', code: 'PS-P-1004', category: 'pendantset', image: gd('11X_y1oy0e0I5bwH8ipTpX6KpVV8jZwbq') },
  { id: 233, name: 'Pendant Set', code: 'PS-P-1005', category: 'pendantset', image: gd('1UsyHf0gMMsbYjoo4AC6dEMA5HbAJ04pf') },
  { id: 234, name: 'Pendant Set', code: 'PS-P-1006', category: 'pendantset', image: gd('1hSFU3j6PPwzZRjEoBjEjAQb5vW3qsSFX') },
  { id: 235, name: 'Pendant Set', code: 'PS-P-1007', category: 'pendantset', image: gd('1XpXXu4AashTlYSjltD8i8a59UkZSDZPU') },
  { id: 236, name: 'Pendant Set', code: 'PS-P-1008', category: 'pendantset', image: gd('1b0UngIXcmibfTSOhYhGxLW-Mqr00kJeU') },
  { id: 237, name: 'Pendant Set', code: 'PS-P-1300', category: 'pendantset', image: gd('19Re1Cez_RPDxsYbgx5d52CyRMgfNHaLS') },
  { id: 238, name: 'Pendant Set', code: 'PS-P-1301', category: 'pendantset', image: gd('1Y1UBdZ7ES2U6GWQJRzi4w-5ECoQFHT0F') },
  { id: 239, name: 'Pendant Set', code: 'PS-P-1302', category: 'pendantset', image: gd('1nwcnzJJAgzi1mhFnI8Bq2OA7aoSVqOmB') },
  { id: 240, name: 'Pendant Set', code: 'PS-P-1303', category: 'pendantset', image: gd('1EEOCFdtCpt_6O5R9H4-1BK-POaMdRM0p') },
  { id: 241, name: 'Pendant Set', code: 'PS-P-1304', category: 'pendantset', image: gd('1mnbNg3jxW1l73BQi9_XfAwHFpE3cLaoi') },
  { id: 242, name: 'Pendant Set', code: 'PS-P-1306', category: 'pendantset', image: gd('13JxJ09HfDw1mPxGFHcQx_qOobLojHtrX') },
  { id: 243, name: 'Pendant Set', code: 'PS-P-1307', category: 'pendantset', image: gd('1qicB48jDS9XQWB4Rj4gSOHfXxAIYTX5o') },
  { id: 244, name: 'Pendant Set', code: 'PS-P-1308', category: 'pendantset', image: gd('1hF8LsbTtfxI8iJQUuDLIMXVK_AV-Y71o') },
  { id: 245, name: 'Pendant Set', code: 'PS-P-1309', category: 'pendantset', image: gd('1TtUuq5UlVfyZgge011HIBaZEjMZhq4p5') },
  { id: 246, name: 'Pendant Set', code: 'PS-P-1310', category: 'pendantset', image: gd('19HQfdp8w-GwwHioCja_RCHLAdzoM4YCA') },
  { id: 247, name: 'Pendant Set', code: 'PS-P-1311', category: 'pendantset', image: gd('1CRAMpr4IpCChcRBYHO_Yk8TWPXhRIYHU') },
  { id: 248, name: 'Pendant Set', code: 'PS-P-1312', category: 'pendantset', image: gd('1R5_636_BjJvmUTxZYroOXyvrmpV0iGH3') },
  { id: 249, name: 'Pendant Set', code: 'PS-P-1313', category: 'pendantset', image: gd('1Rhu_kCrpWH3QDD_wLCimWEcYn3dXEo9P') },
  { id: 250, name: 'Pendant Set', code: 'PS-P-1314', category: 'pendantset', image: gd('1JUYw_I6w21lVPbKBha90zI2Ityc88Omp') },
  { id: 251, name: 'Pendant Set', code: 'PS-P-1315', category: 'pendantset', image: gd('1vnCfXAu2tLK8BjcSiHbJaQ0-nGpDpkCz') },
  { id: 252, name: 'Pendant Set', code: 'PS-P-1316', category: 'pendantset', image: gd('1jsXuj2OTSDU2KbehNLDSRKld_1UWykWg') },
  { id: 253, name: 'Pendant Set', code: 'PS-P-1317', category: 'pendantset', image: gd('1FxSrkDraSG4d924PZAUJC82o28DHURhr') },
  { id: 254, name: 'Pendant Set', code: 'PS-P-1318', category: 'pendantset', image: gd('1EzbvxBHM_IHxSnzLhNqVh5guicwsYTks') },
  { id: 255, name: 'Pendant Set', code: 'PS-P-1319', category: 'pendantset', image: gd('1TPzk0IY-AkfFp6G5q_vrbXBz3v5m6htA') },
  { id: 256, name: 'Pendant Set', code: 'PS-P-1320', category: 'pendantset', image: gd('11GSrBKeZwZv2CCCQNIVlRHLJhPFGXssl') },
  { id: 257, name: 'Pendant Set', code: 'PS-P-1321', category: 'pendantset', image: gd('10smx4MGVVKFZDxOWps6A1YW7FxSByzhw') },
  { id: 258, name: 'Pendant Set', code: 'PS-P-1322', category: 'pendantset', image: gd('15Jmjc3_ZRncr9uCIiXOHw7U-g1JtXwvt') },
  { id: 259, name: 'Pendant Set', code: 'PS-P-1323', category: 'pendantset', image: gd('1zigvXfcrlqiSC3OswNQm9ugqjZXumznh') },
  { id: 260, name: 'Pendant Set', code: 'PS-P-1324', category: 'pendantset', image: gd('1INfENpUqvfJTNsvtaZoZokjhQDaKTFpN') },
  { id: 261, name: 'Pendant Set', code: 'PS-P-1325', category: 'pendantset', image: gd('14wBwHjlrEvXeMQIbnzB2dfAoB6ox3Y4F') },
  { id: 262, name: 'Pendant Set', code: 'PS-P-1326', category: 'pendantset', image: gd('1pKQtIE0aahwgK_T2_Wc4HACOP_DzN83u') },
  { id: 263, name: 'Pendant Set', code: 'PS-P-1327', category: 'pendantset', image: gd('1dv-RaxUAj4VkjjLADIGi6ku3IJgRAsWQ') },
  { id: 264, name: 'Pendant Set', code: 'PS-P-1328', category: 'pendantset', image: gd('1mbnjk7iA6cmV7zx6cotAZ5y-HmFjYaxo') },
  { id: 265, name: 'Pendant Set', code: 'PS-P-1329', category: 'pendantset', image: gd('1yJ123Au27CSbsOBAgv2mqh2T-bEZQtfi') },
  { id: 266, name: 'Pendant Set', code: 'PS-P-1330', category: 'pendantset', image: gd('1kePeFeXbxGkc2JXYpttn1V92BJ9NMYg8') },
  { id: 267, name: 'Pendant Set', code: 'PS-P-1331', category: 'pendantset', image: gd('1weAy94wQDGeQlChZ5OedcbWuGaXHs6Dt') },
  { id: 268, name: 'Pendant Set', code: 'PS-P-1332', category: 'pendantset', image: gd('1YSB_4oK-uuM665p4jRN8MrfofUX_Jui2') },
  { id: 269, name: 'Pendant Set', code: 'PS-P-1333', category: 'pendantset', image: gd('1XvM2cYjxMti67L8btqIV8XKqzb-9IET0') },
  { id: 270, name: 'Pendant Set', code: 'PS-P-1334', category: 'pendantset', image: gd('1wxH1TXbfqH5_qR-5NmoRL4ypsOROOMQt') },
  { id: 271, name: 'Pendant Set', code: 'PS-P-1335', category: 'pendantset', image: gd('1_NlRlJX85KECPtrPAhYTujp1MaUvLGLp') },
  { id: 272, name: 'Pendant Set', code: 'PS-P-1336', category: 'pendantset', image: gd('1I5s6AIHiDzUnQVRcVBAJWKnR986d13nz') },
  { id: 273, name: 'Pendant Set', code: 'PS-P-1337', category: 'pendantset', image: gd('1iOsj2UXV6tMe0jP-GfGwHURb0iP5tYXD') },
  { id: 274, name: 'Pendant Set', code: 'PS-P-1338', category: 'pendantset', image: gd('1pExnqkJGa3oFzhK9NBLex533WmHafMBp') },
  { id: 275, name: 'Pendant Set', code: 'PS-P-1339', category: 'pendantset', image: gd('1zZ7Ap-Sa6DGAkTrFnllaCMR1J0DgNP5_') },
  { id: 276, name: 'Pendant Set', code: 'PS-P-1340', category: 'pendantset', image: gd('12QHzgbR63v0rr0KGx5OjHRk-9SRFfDV7') },
  { id: 277, name: 'Pendant Set', code: 'PS-P-1341', category: 'pendantset', image: gd('1EupOuaDknr2VDHYAVjqh1GCo3Errx0SL') },
  { id: 278, name: 'Pendant Set', code: 'PS-P-1342', category: 'pendantset', image: gd('1g6Bcs1cfGnMxTwtqjqyTSY1kIAcEKh0K') },
  { id: 279, name: 'Pendant Set', code: 'PS-P-1343', category: 'pendantset', image: gd('1-0UJd8WwfyRgpGv6PM7VW5rCMLEf0W7L') },
  { id: 280, name: 'Pendant Set', code: 'PS-P-1344', category: 'pendantset', image: gd('15TUSL05cieqGRUfIgdp-qvg5NPWoj77x') },
  { id: 281, name: 'Pendant Set', code: 'PS-P-1345', category: 'pendantset', image: gd('1M4xS-QXCfMhpiq8DuohQmLoNXGgpHq6S') },
  { id: 282, name: 'Pendant Set', code: 'PS-P-1346', category: 'pendantset', image: gd('1kh-ETRdksBXgLwZLb1seM9s61aJbUohv') },
  { id: 283, name: 'Pendant Set', code: 'PS-P-1347', category: 'pendantset', image: gd('1rT_RmGb5v_KIIca-hUynJGyC041bHL8P') },
  { id: 284, name: 'Pendant Set', code: 'PS-P-1348', category: 'pendantset', image: gd('1qMWI1vtqBErHCFwcVk9cyH4DEy5ezNE5') },
  { id: 285, name: 'Pendant Set', code: 'PS-P-1349', category: 'pendantset', image: gd('1iMgO-kRZnFffP6YzO-YrPSVuKnxn-nJ2') },
  { id: 286, name: 'Pendant Set', code: 'PS-P-1350', category: 'pendantset', image: gd('1zgYRT8kRvNdSNu7y2-V3m9tLVCk0nFSU') },

  // ── Mangalsutra (MS) ─────────────────────────────────────────────────────
  { id: 287, name: 'Mangalsutra', code: 'MS-1014', category: 'ms', image: gd('1x1jmu6RYLEVRK4em3Nq2A6duKihAcP08') },
  { id: 288, name: 'Mangalsutra', code: 'MS-1015', category: 'ms', image: gd('16Ai2zaHiYO8LzIiQUsIJTXABnzGmzQRs') },
  { id: 289, name: 'Mangalsutra', code: 'MS-1016', category: 'ms', image: gd('1-q-ydQYsx9NqdUPlziLhJPJJb7SJZlDf') },
  { id: 290, name: 'Mangalsutra', code: 'MS-1017', category: 'ms', image: gd('1xA3n_4ZwhUnvj278bgVLhG4khe2nA7p4') },
  { id: 291, name: 'Mangalsutra', code: 'MS-1018', category: 'ms', image: gd('1fRFIFkfv9BN2GWq3NoctiFm4JhO61WXI') },
  { id: 292, name: 'Mangalsutra', code: 'MS-1019', category: 'ms', image: gd('15ND4q6PZNCevn79aCINCTLfKM4f7jKYr') },
  { id: 293, name: 'Mangalsutra', code: 'MS-1020', category: 'ms', image: gd('1v3KHinsI1dmGXTDyGuTQfweQV2er0_7O') },
  { id: 294, name: 'Mangalsutra', code: 'MS-1021', category: 'ms', image: gd('1b2JSAilxvZzwQwRWJLMlf5H7Ms0KHAVq') },
  { id: 295, name: 'Mangalsutra', code: 'MS-1022', category: 'ms', image: gd('1pQWyTX2lLQJoVmIDlUlBlwHeleC5UOIW') },
  { id: 296, name: 'Mangalsutra', code: 'MS-1023', category: 'ms', image: gd('1y1NJhM5Ibxizd0dhfQ60iOMIV477hqw5') },
  { id: 297, name: 'Mangalsutra', code: 'MS-1024', category: 'ms', image: gd('19LSBDiI06ZFEbAuAWRx0lkf2Tj1sLCkY') },
  { id: 298, name: 'Mangalsutra', code: 'MS-1025', category: 'ms', image: gd('13MxUu0gRsRzJmzfJpXHzEtrCF9hmM_yV') },
  { id: 299, name: 'Mangalsutra', code: 'MS-1026', category: 'ms', image: gd('1gaJGKOOY09rB-IZiD__dEQvNO7TXv6iV') },
  { id: 300, name: 'Mangalsutra', code: 'MS-1027', category: 'ms', image: gd('1lcEqJlUUlJBir1qtvSX8lXMJ_nf8kXx9') },
  { id: 301, name: 'Mangalsutra', code: 'MS-1028', category: 'ms', image: gd('1ZlizLjDmQycko-DPJR_yxpr84xRQuTbQ') },
  { id: 302, name: 'Mangalsutra', code: 'MS-1029', category: 'ms', image: gd('1PB2fvo6WD1obczU1V6o_aA4CNshBiEwH') },
  { id: 303, name: 'Mangalsutra', code: 'MS-1030', category: 'ms', image: gd('1h3gdt3sFBJKSUJRrVSnsQWPYJ0-MMzfM') },
  { id: 304, name: 'Mangalsutra', code: 'MS-1031', category: 'ms', image: gd('1l654gqoFdNi11rGxuogtLuwfG4yKV6AP') },
  { id: 305, name: 'Mangalsutra', code: 'MS-1032', category: 'ms', image: gd('1Q-oRGMy1oUKnVpmGn7aohDezIP2tkmUQ') },
  { id: 306, name: 'Mangalsutra', code: 'MS-1033', category: 'ms', image: gd('1-6GgACoe6uFlo0IY6OlDdV-ZHkPscIyq') },
  { id: 307, name: 'Mangalsutra', code: 'MS-1034', category: 'ms', image: gd('1OSKriLPcAYx4xDBJpnnBNUJVyzS62OPu') },
  { id: 308, name: 'Mangalsutra', code: 'MS-1035', category: 'ms', image: gd('1ldpTGtIwQoEL3_Ko59QN2c69pSrskIzW') },
  { id: 309, name: 'Mangalsutra', code: 'MS-1036', category: 'ms', image: gd('1YIZh2wgYoVlGwTjOaR06qEdUionORiRH') },
  { id: 310, name: 'Mangalsutra', code: 'MS-1037', category: 'ms', image: gd('1HgW_W2F-z6uDxFKpyxRnQ_dW4usYPDoe') },
  { id: 311, name: 'Mangalsutra', code: 'MS-1038', category: 'ms', image: gd('19BJkuUvmEcaB8RePyxYgBmCfYvH8HZH3') },
  { id: 312, name: 'Mangalsutra', code: 'MS-1039', category: 'ms', image: gd('1q4I4cyAhQkFbX3CYYS5OcRacyM7B3rdd') },
  { id: 313, name: 'Mangalsutra', code: 'MS-1040', category: 'ms', image: gd('18vTY-WcJjqWms-AMJOxhfJUCUmYoBSB7') },
  { id: 314, name: 'Mangalsutra', code: 'MS-1041', category: 'ms', image: gd('1HE5zc6WBhP5ZnMfBIu_kOOSSaKDrCL7l') },
  { id: 315, name: 'Mangalsutra', code: 'MS-1042', category: 'ms', image: gd('1jXB24dE3DfS0QftRQDdcgcDt5V6oObcW') },
  { id: 316, name: 'Mangalsutra', code: 'MS-1043', category: 'ms', image: gd('1lVHezLNMC81dfkiXKrpfuG4UR9EMopuS') },
  { id: 317, name: 'Mangalsutra', code: 'MS-1044', category: 'ms', image: gd('1qOexiPbWJKAxyJWkNdU88DG8UjfOXcJr') },
  { id: 318, name: 'Mangalsutra', code: 'MS-1045', category: 'ms', image: gd('1mNcKDP0GDeX0BFP16lqNVIJJwurPcq1n') },
  { id: 319, name: 'Mangalsutra', code: 'MS-1046', category: 'ms', image: gd('1pt8p-lQ_gyPfbWrXiDYixihc2TrERphq') },
  { id: 320, name: 'Mangalsutra', code: 'MS-1047', category: 'ms', image: gd('1DIG_4NRdm3O-8lIg1G4Wb-k06oiH5jpL') },
  { id: 321, name: 'Mangalsutra', code: 'MS-1048', category: 'ms', image: gd('17tPUICiSgCi4CiXYjKTF3S129ntnTN7C') },
  { id: 322, name: 'Mangalsutra', code: 'MS-1049', category: 'ms', image: gd('1p4Xm5u7udYZRty8b7bBwIMupwz8vt0TO') },
  { id: 323, name: 'Mangalsutra', code: 'MS-1050', category: 'ms', image: gd('17Mv7TTTpkSNxkt_BuXdRlOVkttN6f1g2') },
  { id: 324, name: 'Mangalsutra', code: 'MS-1051', category: 'ms', image: gd('1nNQ1vBAWeJ4tEHorYa2waCcq6P20pdml') },
  { id: 325, name: 'Mangalsutra', code: 'MS-1052', category: 'ms', image: gd('1DnGuBlUkmJiYBA32AFohwQSkwBibZHm_') },
  { id: 326, name: 'Mangalsutra', code: 'MS-1053', category: 'ms', image: gd('1wNvVlSR5IxxhFfduyhaB13DqnoN7mBob') },
  { id: 327, name: 'Mangalsutra', code: 'MS-1054', category: 'ms', image: gd('1a4LA_kaepskoTQ7ezwn24-ZopHhwD1OO') },
  { id: 328, name: 'Mangalsutra', code: 'MS-1055', category: 'ms', image: gd('19rQ93Zy5JTEoq3SI6Db8TU46QcbEn-ls') },
  { id: 329, name: 'Mangalsutra', code: 'MS-1056', category: 'ms', image: gd('1fnwK2GHoCbNMLnKF0NZ6Bj62xzDesMuk') },
  { id: 330, name: 'Mangalsutra', code: 'MS-1057', category: 'ms', image: gd('1kKkrQmAEiLu-kjEW-TN4olcDYyuMOl0H') },
  { id: 331, name: 'Mangalsutra', code: 'MS-1058', category: 'ms', image: gd('1cAFg-ADMQMivvzy8XVUSiml7cBZOKN8t') },
  { id: 332, name: 'Mangalsutra', code: 'MS-1059', category: 'ms', image: gd('10XVU2SahXN5_l5pxgJUp8MhgHQq3y1uT') },
  { id: 333, name: 'Mangalsutra', code: 'MS-1060', category: 'ms', image: gd('1cDlPbthDjxQhUSMQJ9jDmGsA21BPMc3K') },
  { id: 334, name: 'Mangalsutra', code: 'MS-1061', category: 'ms', image: gd('1OcmjMRoIx-TkkuLl-gLTkhJG6w-7jmje') },
  { id: 335, name: 'Mangalsutra', code: 'MS-1062', category: 'ms', image: gd('1DB4Fhs9p6563SdQDC9oiXUt1ExvfMjSh') },
  { id: 336, name: 'Mangalsutra', code: 'MS-1063', category: 'ms', image: gd('1aZ2Hk-UOwrAno8seBz2Phyr0hFck6TJy') },
];

export const ABOUT_CARDS = [
  {
    icon: '💎',
    title: 'BIS Hallmarked',
    text: 'All our jewellery carries official BIS Hallmark certification, guaranteeing authenticity and purity you can trust.',
    badge: { label: 'Certified', color: 'gold' },
  },
  {
    icon: '⚖️',
    title: 'Gold Purity',
    text: 'We deal in all standard gold purities to suit every need:',
    purityTable: [
      { karat: '24K', purity: '99.9%', desc: 'Pure Gold' },
      { karat: '22K', purity: '91.6%', desc: 'Hallmark' },
      { karat: '18K', purity: '75.0%', desc: 'Diamond Sets' },
      { karat: '14K', purity: '58.5%', desc: 'Export Quality' },
    ],
  },
  {
    icon: '🤝',
    title: 'Our Promise',
    text: 'Transparent pricing, lifetime buyback, free resizing, and complete after-sales support — always.',
    badge: { label: 'Trusted Since 2009', color: 'green' },
  },
  {
    icon: '🏪',
    title: 'About Us',
    text: 'Harshita Marketing is a trusted name in fine jewellery, specialising in gold, diamond, and kundan pieces crafted for every occasion.',
  },
];

export const CONTACT_INFO = {
  phone: '+91 88878 78193',
  whatsapp: '+91 88878 78193',
  email: 'harshitamarketingvns@gmail.com',
  address: 'Gokuldham Dipo Colony\nSalarpur, Varanasi\nUP – 221007',
  hours: 'Mon – Sat: 10 am – 8 pm',
};
